-- Add new enum values to OfferStatus
ALTER TYPE "OfferStatus" ADD VALUE IF NOT EXISTS 'PENDING_APPROVAL';
ALTER TYPE "OfferStatus" ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE "OfferStatus" ADD VALUE IF NOT EXISTS 'VIEWED';
ALTER TYPE "OfferStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
ALTER TYPE "OfferStatus" ADD VALUE IF NOT EXISTS 'COUNTERED';

-- Alter Table Company
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "offerApprovalRequired" BOOLEAN NOT NULL DEFAULT false;

-- Alter Table Offer
ALTER TABLE "Offer" 
  ADD COLUMN IF NOT EXISTS "fixedCtc" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "variableCtc" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "joiningBonus" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "employmentType" TEXT NOT NULL DEFAULT 'FULL_TIME',
  ADD COLUMN IF NOT EXISTS "probation" TEXT,
  ADD COLUMN IF NOT EXISTS "location" TEXT,
  ADD COLUMN IF NOT EXISTS "benefits" TEXT,
  ADD COLUMN IF NOT EXISTS "approvalStatus" TEXT NOT NULL DEFAULT 'NOT_REQUIRED',
  ADD COLUMN IF NOT EXISTS "approvedBy" TEXT,
  ADD COLUMN IF NOT EXISTS "approvedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "createdBy" TEXT,
  ADD COLUMN IF NOT EXISTS "sentAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "viewedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "acceptedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "rejectedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "rejectionReason" TEXT,
  ADD COLUMN IF NOT EXISTS "withdrawalReason" TEXT,
  ADD COLUMN IF NOT EXISTS "counterNote" TEXT,
  ADD COLUMN IF NOT EXISTS "version" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "supersededById" TEXT,
  ADD COLUMN IF NOT EXISTS "tokenHash" TEXT,
  ADD COLUMN IF NOT EXISTS "tokenExpiresAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "letterContent" TEXT,
  ADD COLUMN IF NOT EXISTS "internalNotes" TEXT;

-- Create Unique Index on Offer tokenHash
CREATE UNIQUE INDEX IF NOT EXISTS "Offer_tokenHash_key" ON "Offer"("tokenHash");
